/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneioif;

import javax.swing.JOptionPane;

/**
 *
 * @author Andre
 */
public class JFrameCadastroJogadores extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCadastroJogadores
     */
    public JFrameCadastroJogadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbJogador1 = new javax.swing.JLabel();
        tfJogador1 = new javax.swing.JTextField();
        lbJogador2 = new javax.swing.JLabel();
        tfJogador2 = new javax.swing.JTextField();
        lbJogador3 = new javax.swing.JLabel();
        tfJogador3 = new javax.swing.JTextField();
        lbJogador4 = new javax.swing.JLabel();
        tfJogador4 = new javax.swing.JTextField();
        btIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jogadores");

        lbJogador1.setText("Jogador 1:");

        tfJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJogador1ActionPerformed(evt);
            }
        });

        lbJogador2.setText("Jogador 2:");

        tfJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJogador2ActionPerformed(evt);
            }
        });

        lbJogador3.setText("Jogador 3:");

        tfJogador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJogador3ActionPerformed(evt);
            }
        });

        lbJogador4.setText("Jogador 4:");

        tfJogador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJogador4ActionPerformed(evt);
            }
        });

        btIniciar.setText("Iniciar Torneio");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbJogador1)
                        .addGap(18, 18, 18)
                        .addComponent(tfJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbJogador2)
                                .addGap(18, 18, 18)
                                .addComponent(tfJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbJogador3)
                                .addGap(18, 18, 18)
                                .addComponent(tfJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbJogador4)
                                .addGap(18, 18, 18)
                                .addComponent(tfJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(755, Short.MAX_VALUE)
                .addComponent(btIniciar)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJogador1)
                    .addComponent(tfJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJogador2)
                    .addComponent(tfJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJogador3)
                    .addComponent(tfJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJogador4)
                    .addComponent(tfJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(btIniciar)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJogador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJogador1ActionPerformed

    private void tfJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJogador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJogador2ActionPerformed

    private void tfJogador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJogador3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJogador3ActionPerformed

    private void tfJogador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJogador4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJogador4ActionPerformed

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        ControladorTorneio cTorneio = new ControladorTorneio();
        
        Jogador j;
        
        if(tfJogador1.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Preencha o nome do jogador 1.");
        else  {
            j = new Jogador(tfJogador1.getText());
            cTorneio.cadastrarJogador(j);
        }
        j = new Jogador(tfJogador2.getText()); 
        cTorneio.cadastrarJogador(j);
        j = new Jogador(tfJogador3.getText()); 
        cTorneio.cadastrarJogador(j);
        j = new Jogador(tfJogador4.getText()); 
        cTorneio.cadastrarJogador(j);
        
        JFramePartidas jp = new JFramePartidas(cTorneio);
        jp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btIniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbJogador1;
    private javax.swing.JLabel lbJogador2;
    private javax.swing.JLabel lbJogador3;
    private javax.swing.JLabel lbJogador4;
    private javax.swing.JTextField tfJogador1;
    private javax.swing.JTextField tfJogador2;
    private javax.swing.JTextField tfJogador3;
    private javax.swing.JTextField tfJogador4;
    // End of variables declaration//GEN-END:variables
}
