/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneioif;

import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author Andre
 */
public class JFramePartidas extends javax.swing.JFrame {

    /**
     * Creates new form JFramePartidas
     */
    public JFramePartidas(ControladorTorneio cTorneio) {
        initComponents();
        this.cTorneio = cTorneio;
        exibirPartidas();    
    }

    private void exibirPartidas() {
        ArrayList<Partida> partidas = cTorneio.iniciarTorneio();
    
        Iterator<Partida> i = partidas.iterator();

        Partida p = i.next();
        this.rbPartida1Jogador1.setText(p.getJogador1().getNome());
        this.rbPartida1Jogador2.setText(p.getJogador2().getNome());

        p = i.next();
        this.rbPartida2Jogador1.setText(p.getJogador1().getNome());
        this.rbPartida2Jogador2.setText(p.getJogador2().getNome());
        
    }
    
    
    private ControladorTorneio cTorneio;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPartida1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lbPartida1 = new javax.swing.JLabel();
        rbPartida1Jogador1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbPartida1Jogador2 = new javax.swing.JRadioButton();
        lbPartida2 = new javax.swing.JLabel();
        rbPartida2Jogador1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbPartida2Jogador2 = new javax.swing.JRadioButton();
        lbPartida3 = new javax.swing.JLabel();
        rbPartida3Jogador1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbPartida3Jogador2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Partidas");

        lbPartida1.setText("Partida 1:");

        bgPartida1.add(rbPartida1Jogador1);
        rbPartida1Jogador1.setText("Nome do Jogador 1");
        rbPartida1Jogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPartida1Jogador1ActionPerformed(evt);
            }
        });

        jLabel3.setText("x");

        bgPartida1.add(rbPartida1Jogador2);
        rbPartida1Jogador2.setText("Nome do Jogador 2");
        rbPartida1Jogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPartida1Jogador2ActionPerformed(evt);
            }
        });

        lbPartida2.setText("Partida 2:");

        bgPartida1.add(rbPartida2Jogador1);
        rbPartida2Jogador1.setText("Nome do Jogador 1");

        jLabel4.setText("x");

        bgPartida1.add(rbPartida2Jogador2);
        rbPartida2Jogador2.setText("Nome do Jogador 2");

        lbPartida3.setText("Partida 3:");

        bgPartida1.add(rbPartida3Jogador1);
        rbPartida3Jogador1.setText("Nome do Jogador 1");

        jLabel5.setText("x");

        bgPartida1.add(rbPartida3Jogador2);
        rbPartida3Jogador2.setText("Nome do Jogador 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbPartida2)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(rbPartida2Jogador1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(rbPartida2Jogador2)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(lbPartida1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(rbPartida1Jogador1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(rbPartida1Jogador2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPartida3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(rbPartida3Jogador1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(rbPartida3Jogador2)))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(lbPartida1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPartida1Jogador1)
                            .addComponent(jLabel3)
                            .addComponent(rbPartida1Jogador2))
                        .addGap(18, 18, 18)
                        .addComponent(lbPartida2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbPartida3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPartida3Jogador1)
                            .addComponent(jLabel5)
                            .addComponent(rbPartida3Jogador2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPartida2Jogador1)
                    .addComponent(jLabel4)
                    .addComponent(rbPartida2Jogador2))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPartida1Jogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPartida1Jogador1ActionPerformed
        this.rbPartida3Jogador1.setText(this.rbPartida1Jogador1.getText());
    }//GEN-LAST:event_rbPartida1Jogador1ActionPerformed

    private void rbPartida1Jogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPartida1Jogador2ActionPerformed
        this.rbPartida3Jogador1.setText(this.rbPartida1Jogador2.getText());
    }//GEN-LAST:event_rbPartida1Jogador2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPartida1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbPartida1;
    private javax.swing.JLabel lbPartida2;
    private javax.swing.JLabel lbPartida3;
    private javax.swing.JRadioButton rbPartida1Jogador1;
    private javax.swing.JRadioButton rbPartida1Jogador2;
    private javax.swing.JRadioButton rbPartida2Jogador1;
    private javax.swing.JRadioButton rbPartida2Jogador2;
    private javax.swing.JRadioButton rbPartida3Jogador1;
    private javax.swing.JRadioButton rbPartida3Jogador2;
    // End of variables declaration//GEN-END:variables
}
